export interface EmojiEntry {
  readonly emoji: string;
  readonly name: string;
  readonly keywords: readonly string[];
}

type CatalogRow = readonly [emoji: string, name: string, keywords: string];

const CATALOG_ROWS: readonly CatalogRow[] = [
  ["🐙", "octopus", "bb tentacle sea animal"],
  ["🛠️", "hammer and wrench", "tools build api server backend fix"],
  ["🧩", "puzzle piece", "extension plugin module integration"],
  ["📱", "mobile phone", "ios android app device"],
  ["📚", "books", "docs documentation library read"],
  ["☁️", "cloud", "infra aws cloud terraform weather"],
  ["📡", "satellite antenna", "telecom signal radio network"],
  ["🚀", "rocket", "launch raycast ship deploy fast"],
  ["🔌", "electric plug", "plugin plugins power connector"],
  ["🧠", "brain", "skills mind ai think"],
  ["💻", "laptop", "computer cli dev code"],
  ["🖥️", "desktop computer", "monitor screen desktop"],
  ["⌨️", "keyboard", "type input shortcuts"],
  ["🖱️", "computer mouse", "click pointer"],
  ["🗄️", "file cabinet", "database storage archive data"],
  ["💾", "floppy disk", "save storage disk"],
  ["📦", "package", "box npm library sdk ship"],
  ["⚙️", "gear", "settings config dotfiles engine"],
  ["🔧", "wrench", "fix tool config"],
  ["🔨", "hammer", "build tool"],
  ["🪛", "screwdriver", "tool fix"],
  ["🔩", "nut and bolt", "hardware parts"],
  ["🧰", "toolbox", "tools kit utilities"],
  ["🧪", "test tube", "test qa experiment lab"],
  ["🔬", "microscope", "research science inspect"],
  ["🔭", "telescope", "observe explore space"],
  ["🧬", "dna", "biology genome"],
  ["🤖", "robot", "bot ai agent automation ml"],
  ["👾", "alien monster", "game retro arcade"],
  ["🎮", "video game", "game controller play"],
  ["🕹️", "joystick", "game arcade"],
  ["🎲", "game die", "dice random chance"],
  ["♟️", "chess pawn", "chess strategy game"],
  ["🧭", "compass", "navigation direction explore"],
  ["🗺️", "world map", "map travel geo"],
  ["📍", "round pushpin", "location pin place"],
  ["🌐", "globe with meridians", "web internet site frontend"],
  ["🌍", "globe europe africa", "world earth planet"],
  ["🌎", "globe americas", "world earth planet"],
  ["🌏", "globe asia australia", "world earth planet"],
  ["🔐", "locked with key", "auth security secret lock"],
  ["🔑", "key", "auth password secret access"],
  ["🛡️", "shield", "security protect defense"],
  ["🔒", "locked", "lock private secure"],
  ["🚨", "police light", "alert incident oncall alarm"],
  ["🔔", "bell", "notification alert ring"],
  ["📈", "chart increasing", "metrics growth analytics stats"],
  ["📉", "chart decreasing", "metrics decline"],
  ["📊", "bar chart", "analytics dashboard stats data"],
  ["🧮", "abacus", "math count calculate"],
  ["💬", "speech balloon", "chat message slack talk"],
  ["🗨️", "left speech bubble", "chat comment"],
  ["✉️", "envelope", "mail email letter"],
  ["📧", "e-mail", "mail email"],
  ["📨", "incoming envelope", "inbox mail"],
  ["📬", "mailbox", "mail post"],
  ["📞", "telephone receiver", "phone call voice"],
  ["☎️", "telephone", "phone call"],
  ["📟", "pager", "oncall page alert"],
  ["🎙️", "studio microphone", "voice audio podcast record"],
  ["🎧", "headphone", "audio music listen"],
  ["🎵", "musical note", "music audio song"],
  ["🎸", "guitar", "music rock"],
  ["🎹", "musical keyboard", "piano music"],
  ["🥁", "drum", "music beat"],
  ["🎨", "artist palette", "design art paint ui color"],
  ["🖌️", "paintbrush", "paint design art"],
  ["✏️", "pencil", "edit write draw"],
  ["🖊️", "pen", "write sign"],
  ["📝", "memo", "notes write blog todo"],
  ["📓", "notebook", "notes journal"],
  ["📒", "ledger", "notes accounting"],
  ["📔", "notebook decorative cover", "journal diary"],
  ["📖", "open book", "read docs guide"],
  ["📜", "scroll", "scripts history document"],
  ["📄", "page facing up", "document file page"],
  ["📋", "clipboard", "tasks list checklist"],
  ["📌", "pushpin", "pin important"],
  ["📎", "paperclip", "attachment clip"],
  ["🗂️", "card index dividers", "organize files folders"],
  ["📁", "file folder", "folder files directory"],
  ["📂", "open file folder", "folder files"],
  ["🗃️", "card file box", "archive records"],
  ["🗑️", "wastebasket", "trash delete"],
  ["🔍", "magnifying glass tilted left", "search find look"],
  ["🔎", "magnifying glass tilted right", "search find inspect"],
  ["💡", "light bulb", "idea insight"],
  ["🔦", "flashlight", "light explore"],
  ["🕯️", "candle", "light calm"],
  ["🔥", "fire", "hot burn lit"],
  ["⚡", "high voltage", "fast power electric lightning"],
  ["💥", "collision", "boom crash"],
  ["✨", "sparkles", "magic new shiny"],
  ["⭐", "star", "favorite star"],
  ["🌟", "glowing star", "shine favorite"],
  ["💫", "dizzy", "star swirl"],
  ["☄️", "comet", "space fast"],
  ["🪐", "ringed planet", "space saturn planet"],
  ["🌙", "crescent moon", "night moon"],
  ["☀️", "sun", "sunny day bright"],
  ["🌤️", "sun behind small cloud", "weather day"],
  ["🌈", "rainbow", "color pride"],
  ["🌊", "water wave", "ocean sea surf"],
  ["❄️", "snowflake", "cold winter ice"],
  ["🌪️", "tornado", "storm wind"],
  ["🌋", "volcano", "mountain eruption"],
  ["🏔️", "snow-capped mountain", "mountain peak"],
  ["⛰️", "mountain", "hike peak"],
  ["🏕️", "camping", "tent outdoors"],
  ["🏝️", "desert island", "beach vacation"],
  ["🏜️", "desert", "sand dry"],
  ["🌵", "cactus", "desert plant"],
  ["🌲", "evergreen tree", "forest tree"],
  ["🌳", "deciduous tree", "tree nature"],
  ["🌴", "palm tree", "tropical beach"],
  ["🌱", "seedling", "grow sprout new start"],
  ["🌿", "herb", "plant leaf"],
  ["🍀", "four leaf clover", "luck lucky"],
  ["🍁", "maple leaf", "fall autumn canada"],
  ["🍂", "fallen leaf", "autumn"],
  ["🍄", "mushroom", "fungus"],
  ["🌸", "cherry blossom", "flower spring"],
  ["🌻", "sunflower", "flower summer"],
  ["🌹", "rose", "flower love"],
  ["🌷", "tulip", "flower spring"],
  ["🌺", "hibiscus", "flower tropical"],
  ["🪴", "potted plant", "plant home grow"],
  ["🍎", "red apple", "fruit apple"],
  ["🍊", "tangerine", "orange fruit"],
  ["🍋", "lemon", "fruit sour"],
  ["🍌", "banana", "fruit"],
  ["🍉", "watermelon", "fruit summer"],
  ["🍇", "grapes", "fruit wine"],
  ["🍓", "strawberry", "fruit berry"],
  ["🫐", "blueberries", "fruit berry"],
  ["🍒", "cherries", "fruit"],
  ["🍑", "peach", "fruit"],
  ["🍍", "pineapple", "fruit tropical"],
  ["🥝", "kiwi fruit", "fruit"],
  ["🥑", "avocado", "fruit guac"],
  ["🌶️", "hot pepper", "spicy chili"],
  ["🥕", "carrot", "vegetable"],
  ["🌽", "ear of corn", "corn vegetable"],
  ["🥦", "broccoli", "vegetable"],
  ["🍕", "pizza", "food slice"],
  ["🍔", "hamburger", "food burger"],
  ["🌮", "taco", "food mexican"],
  ["🍣", "sushi", "food japanese"],
  ["🍜", "steaming bowl", "ramen noodles soup"],
  ["🥐", "croissant", "bread french"],
  ["🥯", "bagel", "bread breakfast"],
  ["🧇", "waffle", "breakfast"],
  ["🥞", "pancakes", "breakfast"],
  ["🍩", "doughnut", "donut sweet"],
  ["🍪", "cookie", "sweet biscuit"],
  ["🧁", "cupcake", "sweet cake"],
  ["🎂", "birthday cake", "cake party"],
  ["🍰", "shortcake", "cake sweet"],
  ["🍫", "chocolate bar", "sweet candy"],
  ["🍬", "candy", "sweet"],
  ["🍭", "lollipop", "sweet candy"],
  ["🍿", "popcorn", "movie snack"],
  ["☕", "hot beverage", "coffee tea java"],
  ["🍵", "teacup without handle", "tea matcha"],
  ["🧋", "bubble tea", "boba drink"],
  ["🍺", "beer mug", "beer drink"],
  ["🍷", "wine glass", "wine drink"],
  ["🍹", "tropical drink", "cocktail"],
  ["🧊", "ice", "cold cube"],
  ["🧂", "salt", "seasoning"],
  ["🐶", "dog face", "dog pet puppy"],
  ["🐱", "cat face", "cat pet kitten"],
  ["🐭", "mouse face", "mouse"],
  ["🐹", "hamster", "pet"],
  ["🐰", "rabbit face", "bunny"],
  ["🦊", "fox", "animal clever"],
  ["🐻", "bear", "animal"],
  ["🐼", "panda", "animal"],
  ["🐨", "koala", "animal australia"],
  ["🐯", "tiger face", "animal"],
  ["🦁", "lion", "animal king"],
  ["🐮", "cow face", "animal"],
  ["🐷", "pig face", "animal"],
  ["🐸", "frog", "animal"],
  ["🐵", "monkey face", "animal"],
  ["🐔", "chicken", "bird"],
  ["🐧", "penguin", "bird linux"],
  ["🐦", "bird", "tweet"],
  ["🦅", "eagle", "bird"],
  ["🦆", "duck", "bird rubber debug"],
  ["🦉", "owl", "bird wise night"],
  ["🦜", "parrot", "bird"],
  ["🦩", "flamingo", "bird pink"],
  ["🦚", "peacock", "bird"],
  ["🐺", "wolf", "animal"],
  ["🦝", "raccoon", "animal"],
  ["🐴", "horse face", "animal"],
  ["🦄", "unicorn", "magic startup"],
  ["🦓", "zebra", "animal"],
  ["🦒", "giraffe", "animal"],
  ["🐘", "elephant", "animal postgres"],
  ["🦏", "rhinoceros", "animal"],
  ["🦛", "hippopotamus", "animal"],
  ["🐪", "camel", "animal desert"],
  ["🦘", "kangaroo", "animal australia"],
  ["🦥", "sloth", "slow animal"],
  ["🦦", "otter", "animal"],
  ["🦫", "beaver", "animal build"],
  ["🦔", "hedgehog", "animal"],
  ["🐿️", "chipmunk", "squirrel animal"],
  ["🐝", "honeybee", "bee busy"],
  ["🐞", "lady beetle", "bug ladybug"],
  ["🐛", "bug", "bug caterpillar debug"],
  ["🦋", "butterfly", "insect"],
  ["🐌", "snail", "slow"],
  ["🐜", "ant", "insect"],
  ["🕷️", "spider", "web crawler scraper"],
  ["🦂", "scorpion", "animal"],
  ["🐢", "turtle", "slow animal"],
  ["🐍", "snake", "python"],
  ["🦎", "lizard", "reptile"],
  ["🦖", "t-rex", "dinosaur"],
  ["🦕", "sauropod", "dinosaur"],
  ["🐉", "dragon", "myth"],
  ["🐳", "spouting whale", "whale docker"],
  ["🐋", "whale", "ocean"],
  ["🐬", "dolphin", "ocean"],
  ["🦭", "seal", "ocean"],
  ["🐟", "fish", "ocean"],
  ["🐠", "tropical fish", "ocean"],
  ["🐡", "blowfish", "ocean"],
  ["🦈", "shark", "ocean"],
  ["🦀", "crab", "rust ocean"],
  ["🦞", "lobster", "ocean"],
  ["🦐", "shrimp", "ocean"],
  ["🦑", "squid", "ocean"],
  ["🐚", "spiral shell", "shell ocean"],
  ["🪸", "coral", "ocean reef"],
  ["🏠", "house", "home personal"],
  ["🏡", "house with garden", "home"],
  ["🏢", "office building", "work office company"],
  ["🏭", "factory", "build pipeline industry"],
  ["🏗️", "building construction", "build construction wip"],
  ["🏛️", "classical building", "government legacy"],
  ["🏰", "castle", "fortress"],
  ["🗼", "tokyo tower", "tower"],
  ["🗽", "statue of liberty", "new york"],
  ["🌉", "bridge at night", "bridge connect"],
  ["🎡", "ferris wheel", "fun fair"],
  ["🎢", "roller coaster", "fun ride"],
  ["🎪", "circus tent", "circus show"],
  ["🚗", "automobile", "car drive"],
  ["🚕", "taxi", "car"],
  ["🚌", "bus", "transit"],
  ["🚎", "trolleybus", "transit"],
  ["🏎️", "racing car", "fast race"],
  ["🚓", "police car", "police"],
  ["🚑", "ambulance", "health emergency"],
  ["🚒", "fire engine", "fire"],
  ["🚚", "delivery truck", "deliver shipping"],
  ["🚜", "tractor", "farm"],
  ["🚲", "bicycle", "bike cycle"],
  ["🛴", "kick scooter", "scooter"],
  ["🛵", "motor scooter", "scooter"],
  ["🏍️", "motorcycle", "bike"],
  ["🚂", "locomotive", "train"],
  ["🚄", "high-speed train", "train fast"],
  ["🚇", "metro", "subway transit"],
  ["🚊", "tram", "transit"],
  ["✈️", "airplane", "flight travel"],
  ["🛩️", "small airplane", "flight"],
  ["🛫", "airplane departure", "takeoff launch"],
  ["🚁", "helicopter", "flight"],
  ["🛸", "flying saucer", "ufo alien"],
  ["🛰️", "satellite", "space orbit"],
  ["⛵", "sailboat", "sail boat"],
  ["🚤", "speedboat", "boat fast"],
  ["🛳️", "passenger ship", "ship cruise"],
  ["⚓", "anchor", "harbor ship"],
  ["🪝", "hook", "hooks webhook"],
  ["⛽", "fuel pump", "gas fuel"],
  ["🚦", "traffic light", "status signal"],
  ["🚧", "construction", "wip barrier"],
  ["🏁", "chequered flag", "finish race"],
  ["🚩", "triangular flag", "flag feature"],
  ["🎌", "crossed flags", "japan"],
  ["🏳️", "white flag", "surrender"],
  ["⏰", "alarm clock", "time alarm schedule"],
  ["⏱️", "stopwatch", "timer time benchmark"],
  ["⏳", "hourglass not done", "wait time"],
  ["⌛", "hourglass done", "time"],
  ["📅", "calendar", "date schedule"],
  ["🗓️", "spiral calendar", "schedule plan"],
  ["🎯", "direct hit", "target goal focus"],
  ["🏆", "trophy", "win award"],
  ["🥇", "1st place medal", "gold win"],
  ["🎖️", "military medal", "award"],
  ["🏅", "sports medal", "award"],
  ["⚽", "soccer ball", "football sport"],
  ["🏀", "basketball", "sport"],
  ["🏈", "american football", "sport"],
  ["⚾", "baseball", "sport"],
  ["🎾", "tennis", "sport"],
  ["🏐", "volleyball", "sport"],
  ["🏓", "ping pong", "table tennis sport"],
  ["🏸", "badminton", "sport"],
  ["⛳", "flag in hole", "golf"],
  ["🏹", "bow and arrow", "archery target"],
  ["🎣", "fishing pole", "fishing"],
  ["🥊", "boxing glove", "fight"],
  ["🛹", "skateboard", "skate"],
  ["⛷️", "skier", "ski snow"],
  ["🏄", "person surfing", "surf"],
  ["🧗", "person climbing", "climb"],
  ["🎈", "balloon", "party"],
  ["🎉", "party popper", "celebrate party"],
  ["🎊", "confetti ball", "celebrate"],
  ["🎁", "wrapped gift", "present gift"],
  ["🎀", "ribbon", "gift"],
  ["🪁", "kite", "fly"],
  ["🪀", "yo-yo", "toy"],
  ["🧸", "teddy bear", "toy"],
  ["🪄", "magic wand", "magic"],
  ["🔮", "crystal ball", "predict future magic"],
  ["🧿", "nazar amulet", "protect"],
  ["💎", "gem stone", "diamond ruby jewel"],
  ["💍", "ring", "jewel"],
  ["👑", "crown", "king queen"],
  ["🎩", "top hat", "magic fancy"],
  ["🧢", "billed cap", "hat"],
  ["👓", "glasses", "read view"],
  ["🕶️", "sunglasses", "cool"],
  ["🧳", "luggage", "travel"],
  ["🎒", "backpack", "school travel"],
  ["👟", "running shoe", "run sneaker"],
  ["🧦", "socks", "clothes"],
  ["🧤", "gloves", "clothes"],
  ["🧣", "scarf", "clothes"],
  ["💰", "money bag", "money finance billing"],
  ["💵", "dollar banknote", "money payment"],
  ["💳", "credit card", "payment billing"],
  ["🪙", "coin", "money crypto"],
  ["🏦", "bank", "finance"],
  ["🛒", "shopping cart", "shop store commerce"],
  ["🏪", "convenience store", "store shop"],
  ["🧾", "receipt", "invoice billing"],
  ["⚖️", "balance scale", "law legal balance"],
  ["🩺", "stethoscope", "health doctor"],
  ["💊", "pill", "health medicine"],
  ["🩹", "adhesive bandage", "fix patch heal"],
  ["❤️", "red heart", "love health"],
  ["🧡", "orange heart", "love"],
  ["💛", "yellow heart", "love"],
  ["💚", "green heart", "love"],
  ["💙", "blue heart", "love"],
  ["💜", "purple heart", "love"],
  ["🖤", "black heart", "love"],
  ["🤍", "white heart", "love"],
  ["🔴", "red circle", "red dot"],
  ["🟠", "orange circle", "orange dot"],
  ["🟡", "yellow circle", "yellow dot"],
  ["🟢", "green circle", "green dot ok"],
  ["🔵", "blue circle", "blue dot"],
  ["🟣", "purple circle", "purple dot"],
  ["🟥", "red square", "red"],
  ["🟧", "orange square", "orange"],
  ["🟨", "yellow square", "yellow"],
  ["🟩", "green square", "green"],
  ["🟦", "blue square", "blue"],
  ["🟪", "purple square", "purple"],
  ["🔶", "large orange diamond", "diamond"],
  ["🔷", "large blue diamond", "diamond"],
  ["✅", "check mark button", "done ok yes"],
  ["☑️", "check box with check", "done task"],
  ["❌", "cross mark", "no error"],
  ["❓", "question mark", "question help"],
  ["❗", "exclamation mark", "important"],
  ["♻️", "recycling symbol", "recycle reuse"],
  ["🔁", "repeat button", "loop repeat sync"],
  ["🔄", "counterclockwise arrows", "sync refresh reload"],
  ["🔀", "shuffle tracks", "random merge"],
  ["🔗", "link", "url chain connect"],
  ["⛓️", "chains", "chain blockchain"],
  ["🧲", "magnet", "attract"],
  ["🔋", "battery", "power energy"],
  ["🪫", "low battery", "power"],
  ["🧯", "fire extinguisher", "incident firefight"],
  ["🪜", "ladder", "climb"],
  ["🧱", "brick", "wall build block"],
  ["🪨", "rock", "stone"],
  ["🪵", "wood", "log"],
  ["🛢️", "oil drum", "oil barrel"],
  ["🗝️", "old key", "key legacy"],
  ["🚪", "door", "entry gateway"],
  ["🪟", "window", "windows"],
  ["🛏️", "bed", "sleep"],
  ["🛋️", "couch and lamp", "home living"],
  ["🧹", "broom", "clean cleanup"],
  ["🧺", "basket", "laundry"],
  ["🧼", "soap", "clean"],
  ["🪣", "bucket", "s3 storage bucket"],
  ["🧽", "sponge", "clean"],
  ["🧵", "thread", "thread sew"],
  ["🧶", "yarn", "knit"],
  ["🪡", "sewing needle", "sew"],
  ["🏷️", "label", "tag release version"],
  ["🔖", "bookmark", "save mark"],
  ["📰", "newspaper", "news"],
  ["🗞️", "rolled-up newspaper", "news"],
  ["📮", "postbox", "mail"],
  ["📯", "postal horn", "announce"],
  ["📢", "loudspeaker", "announce broadcast"],
  ["📣", "megaphone", "announce marketing"],
  ["📷", "camera", "photo picture"],
  ["📸", "camera with flash", "photo screenshot"],
  ["🎥", "movie camera", "video film"],
  ["📺", "television", "tv video"],
  ["📻", "radio", "audio broadcast"],
  ["🎬", "clapper board", "film movie"],
  ["🎭", "performing arts", "theater drama"],
  ["🖼️", "framed picture", "image art"],
  ["🧑‍💻", "technologist", "developer coder engineer"],
  ["👷", "construction worker", "build worker"],
  ["🧙", "mage", "wizard magic"],
  ["🥷", "ninja", "stealth"],
  ["🦸", "superhero", "hero"],
  ["👻", "ghost", "spooky"],
  ["💀", "skull", "dead"],
  ["👽", "alien", "space"],
  ["🤠", "cowboy hat face", "western"],
  ["😎", "smiling face with sunglasses", "cool"],
  ["🙂", "slightly smiling face", "smile"],
  ["🤓", "nerd face", "nerd geek"],
  ["🥳", "partying face", "party"],
  ["🫡", "saluting face", "salute"],
  ["👀", "eyes", "look watch review"],
  ["👋", "waving hand", "hello wave"],
  ["👍", "thumbs up", "ok approve"],
  ["🙌", "raising hands", "celebrate"],
  ["💪", "flexed biceps", "strong"],
  ["🤝", "handshake", "deal partner"],
  ["✋", "raised hand", "stop"],
];

export const EMOJI_CATALOG: readonly EmojiEntry[] = CATALOG_ROWS.map(
  ([emoji, name, keywords]) => ({
    emoji,
    name,
    keywords: keywords.split(" "),
  }),
);

const KEYWORD_RULES: ReadonlyArray<readonly [emoji: string, tokens: string]> = [
  ["📡", "telecom sms ims lte 5g volte epdg diameter radio"],
  ["🚀", "raycast launch launcher"],
  ["🔌", "plugin plugins"],
  ["🧠", "skill skills prompts memory"],
  ["🧩", "extension extensions addon addons chrome"],
  ["🐙", "bb"],
  ["📱", "mobile ios android iphone ipad watchos swift kotlin"],
  ["📚", "doc docs documentation wiki handbook guide guides"],
  ["☁️", "infra infrastructure terraform aws cdk cloud gcp azure k8s kubernetes helm eks ecs"],
  ["🛠️", "api server backend service services"],
  ["🌐", "web frontend site website www landing"],
  ["💻", "cli terminal shell tui"],
  ["⚙️", "dotfiles config configs settings"],
  ["🗄️", "db database sql postgres mysql sqlite migrations"],
  ["🤖", "ai ml llm agent agents bot bots model models"],
  ["🧪", "test tests testing qa e2e benchmark benchmarks"],
  ["🎮", "game games"],
  ["🎨", "design ui ux theme themes"],
  ["📝", "notes blog journal writing"],
  ["📜", "script scripts"],
  ["💬", "chat slack discord"],
  ["🔐", "auth security secrets vault"],
  ["🏠", "personal home"],
  ["📦", "lib libs library sdk packages pkg"],
  ["📈", "metrics monitoring observability grafana honeycomb dashboards"],
  ["✉️", "mail email"],
  ["🐳", "docker container containers"],
  ["🦀", "rust"],
  ["🐍", "python"],
  ["🐘", "php"],
];

const KEYWORD_RANK: ReadonlyMap<string, number> = new Map(
  KEYWORD_RULES.flatMap(([, tokens], rank) =>
    tokens.split(" ").map((token) => [token, rank] as const),
  ),
);

export const FALLBACK_EMOJI: readonly string[] = [
  "🦊", "🐳", "🦉", "🌵", "🍀", "🌻", "🍄", "🪐",
  "🌈", "🔥", "🌊", "🍉", "🍋", "🥑", "🧁", "🍩",
  "🎈", "🎯", "🧭", "🪁", "🛸", "⛵", "🚲", "🏔️",
  "🌋", "🏝️", "🦄", "🐝", "🦋", "🐢", "🐧", "🦜",
  "🐬", "🦀", "🌙", "☄️", "💎", "🔮", "🪴", "🎲",
  "🎸", "🧊", "🍁", "🌸", "🐞", "🦩", "🦦", "🐼",
];

export interface ProjectFacts {
  readonly id: string;
  readonly name: string;
  readonly kind: "personal" | "standard";
  readonly paths: readonly string[];
  readonly gitRemoteUrl: string | null;
}

export function tokenize(text: string): string[] {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((token) => token.length > 0);
}

function lastSegment(path: string): string {
  const segments = path.split(/[\\/]+/).filter((segment) => segment.length > 0);
  return segments.at(-1) ?? "";
}

function remoteRepoName(url: string): string {
  return lastSegment(url.replace(/\.git$/, "").replace(/:/g, "/"));
}

export function keywordEmoji(project: ProjectFacts): string | null {
  if (project.kind === "personal") return "🏠";
  const sources = [
    project.name,
    ...project.paths.map(lastSegment),
    project.gitRemoteUrl === null ? "" : remoteRepoName(project.gitRemoteUrl),
  ];
  for (const source of sources) {
    const ranks = tokenize(source).flatMap((token) => {
      const rank = KEYWORD_RANK.get(token);
      return rank === undefined ? [] : [rank];
    });
    if (ranks.length > 0) return KEYWORD_RULES[Math.min(...ranks)]![0];
  }
  return null;
}

export function hashString(value: string): number {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

export function fallbackEmoji(projectId: string, taken: ReadonlySet<string>): string {
  const start = hashString(projectId) % FALLBACK_EMOJI.length;
  for (let offset = 0; offset < FALLBACK_EMOJI.length; offset += 1) {
    const candidate = FALLBACK_EMOJI[(start + offset) % FALLBACK_EMOJI.length]!;
    if (!taken.has(candidate)) return candidate;
  }
  return FALLBACK_EMOJI[start]!;
}

export function autoEmoji(project: ProjectFacts, taken: ReadonlySet<string>): string {
  return keywordEmoji(project) ?? fallbackEmoji(project.id, taken);
}

const graphemes = new Intl.Segmenter(undefined, { granularity: "grapheme" });

export function parseEmoji(input: string): string | null {
  const value = input.trim();
  if (value.length === 0 || value.length > 32) return null;
  const segments = [...graphemes.segment(value)];
  if (segments.length !== 1) return null;
  if (!/\p{Extended_Pictographic}|\p{Regional_Indicator}|⃣/u.test(value)) {
    return null;
  }
  return value;
}

export function searchEmoji(query: string): readonly EmojiEntry[] {
  const terms = tokenize(query);
  if (terms.length === 0) return EMOJI_CATALOG;
  return EMOJI_CATALOG.filter((entry) => {
    const words = [...tokenize(entry.name), ...entry.keywords];
    return terms.every((term) => words.some((word) => word.startsWith(term)));
  });
}
